# Generated by Django 2.0.2 on 2018-04-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keg',
            name='tag',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
