# Generated by Django 2.0.2 on 2018-04-05 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_keg_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='keg',
            name='fill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fill', to='inventory.Fill'),
        ),
    ]
