# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-03 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import common.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_keg_litres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('created', common.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', common.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('litres', models.IntegerField(default=1000)),
            ],
            options={
                'verbose_name': 'batch',
                'verbose_name_plural': 'batches',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('created', common.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', common.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'batch',
                'verbose_name_plural': 'batches',
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='keg',
            name='litres',
            field=models.IntegerField(
                choices=[(50, '50 Litres'), (30, '30 Litres'), (20, '20 Litres')], default=50),
        ),
        migrations.AddField(
            model_name='batch',
            name='beer',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beer', to='inventory.Beer'),
        ),
        migrations.AddField(
            model_name='keg',
            name='batch',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='inventory.Batch'),
        ),
    ]
