# Generated by Django 2.0.2 on 2018-04-11 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('inventory', '0003_keg_fill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keg',
            name='fill',
        ),
        migrations.AddField(
            model_name='fill',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounting.Customer'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='keg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keg', to='inventory.Keg'),
        ),
    ]
