# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-03 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20171203_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ('created',), 'verbose_name': 'beer', 'verbose_name_plural': 'beers'},
        ),
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
