# Generated by Django 2.0.2 on 2018-04-11 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180411_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounting.Customer'),
        ),
    ]
