# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-03 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20171203_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='qbid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fill',
            name='qbid',
            field=models.IntegerField(null=True),
        ),
    ]
